model_def:
  name: catapult
  dt: 1e-2
  substeps: 1
disable_logging: False
num_steps: 100
test_times: 10
lr: 1e-3
loss_func: linear
opt: Adam
seed_getter:
  type: art
  art_params:
    init_pop_size: 200
    cand_size: 10
    refresh_prob: 0.1
  min_steps: 30
  max_steps: 100
  reset_freq: 1000
  max_vel_allowed: 10
  act_std: [10, 10, 10]
max_non_zero_act_steps: 20
mut_dev: 0.05
mut_steps: 1
loss_utils:
  max_epochs: 500
  threshold_sigma: 3
  max_len: 100
  display_freq: 30
  converge_threshold: 1.0e-3
use_gui: False
