model_def:
  name: snake
  frame_rate: 60
  substeps: 10
  num_chains: 8
  chain_length: 1.0
  joint_limit: 160
  joint_type: revolute
  root_height: 2.0
  gravity: False
  ground: True
  collision: True
seed: 1547
disable_logging: False
num_steps: 100
test_times: 10000
lr: 1e-3
loss_func: linear
opt: Adam
seed_getter:
  type: art
  art_params:
    init_pop_size: 10
    cand_size: 10
    refresh_prob: 0.1
  min_steps: 11
  max_steps: 30
  reset_freq: 500
  max_v_allowed: 10
  max_w_allowed: 10
  act_std: [3, 3, 3, 3, 3, 3, 3, 3]
max_non_zero_act_steps: 20
mut_dev: 0.05
mut_steps: 1
loss_utils:
  max_epochs: 500
  threshold_sigma: 3
  max_len: 100
  display_freq: 30
  converge_threshold: 1e-1
use_gui: False
