model_def:
  name: "mpm"
  substeps: 8
seed: 0
use_gpu: True
disable_logging: False
num_steps: 100
test_times: 10000
lr: 1e-3
loss_func: linear
opt: Adam
seed_getter:
  type: art
  art_params:
    init_pop_size: 10
    cand_size: 10
    refresh_prob: 0.1
  min_steps: 50
  max_steps: 300
  reset_freq: 8
  act_std: 1
mut_dev: 0.05
mut_steps: 10
loss_utils:
  max_epochs: 500
  threshold_sigma: 3
  max_len: 100
  display_freq: 30
  converge_threshold: 1.0e-2
