model_def:
  name: "two_balls"
  dt: 0.01
  radius: 0.1
  init_pos: 0.5
  init_vel: 1
  wall_pos: 1.0
  grace_gap: 0.15
seed: 44653
use_gpu: True
disable_logging: False
num_steps: 100
test_times: 10000
lr: 2e-3
loss_func: linear
opt: Adam
seed_getter:
  type: art
  art_params:
    init_pop_size: 10
    cand_size: 10
    refresh_prob: 0.1
  min_steps: 20
  max_steps: 30
  reset_freq: 500
  max_vel_allowed: 20
  act_std: [3, 3]
max_non_zero_act_steps: 20
mut_dev: 0.05
mut_steps: 10
loss_utils:
  max_epochs: 500
  threshold_sigma: 3
  max_len: 100
  display_freq: 30
  converge_threshold: 1.0e-3
use_gui: False
